---
# tasks file for roles/win_ad_install

- name: Installs AD-Domain-Service
  win_feature: 
   name: AD-Domain-Services
   state: present

- name: Ensure a server is a domain controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
#    domain_admin_user:  "{{ ad_admin_user }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  notify:
  - windows_reboot 

- name: List nltest /dclist
  win_command: nltest /dclist:"{{ ad_domain_name }}"
  register: domain_list

- debug:
   var: domain_list
