---
# tasks file for roles/win_service_config
- name: Install a package
  win_chocolatey:
   name: " {{ package_name }} "
   params: " {{ parameters }} "
   state: latest
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Enable a Service
  win_service:
   name: " {{ service_name }} "
   state: started
   start_mode: auto
#   path: C:\
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Creates a firewall rule for service
  win_firewall_rule:
   name: " {{ service_name }} "
   localport: " {{ local_port }} "
   action: allow
   direction: in
   protocol: " {{ protocol_name }} "
   state: present
   enabled: yes


